package com.tracker.repository;

import com.tracker.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    Optional<User> findByEmail(String email);

    boolean existsByEmail(String email);

    Optional<User> findByProviderId(String providerId);
}
//```
//
//        ---
//
//        ## Complete file checklist
//
//        Here is every file that should exist in your project right now. Tick them off in IntelliJ:
//        ```
//        src/main/java/com/tracker/
//        │
//        ├── exception/
//        │   ├── ResourceNotFoundException.java   ← JUST CREATED (was missing)
//        │   └── GlobalExceptionHandler.java      ← FIXED (@Builder.Default + full handlers)
//        │
//        ├── model/
//        │   ├── User.java                        ← from Phase 2
//        │   ├── Opportunity.java                 ← FIXED (@Builder.Default on 2 fields)
//        │   ├── Reminder.java                    ← needed for Phase 5 (create now, below)
//        │   ├── UserPreference.java              ← needed for Phase 5 (create now, below)
//        │   └── enums/
//        │       ├── OpportunityStatus.java       ← from Phase 3
//        │       └── OpportunityType.java         ← from Phase 3
//        │
//        ├── repository/
//        │   ├── UserRepository.java              ← JUST ADDED (may have been missing)
//        │   └── OpportunityRepository.java      ← from Phase 3
//        │
//        ├── service/
//        │   ├── CustomOAuth2UserService.java     ← from Phase 2
//        │   ├── GmailService.java                ← from Phase 3
//        │   └── EmailParserService.java          ← from Phase 3
//        │
//        ├── security/
//        │   ├── JwtAuthFilter.java               ← from Phase 2
//        │   └── OAuth2SuccessHandler.java        ← from Phase 2
//        │
//        ├── config/
//        │   └── SecurityConfig.java              ← from Phase 2
//        │
//        ├── controller/
//        │   └── GmailController.java             ← from Phase 3
//        │
//        ├── util/
//        │   └── JwtUtil.java                     ← from Phase 2
//        │
//        └── TrackerApplication.java              ← auto-generated by Spring Initializr